export const funcionalidadesPorPerfil = [
  {
    group: 'bko',
    name: 'Backoffice Administrator',
    funcionalidades: [
      { name: 'Cadastro/Edição de Estabelecimento' },
      { name: 'Cadastro/Edição de Fornecedor' },
      { name: 'Consulta de Estabelecimento' },
      { name: 'Consulta de Fornecedor' },
      { name: 'Configurar Taxas' },
      { name: 'Cadastro de Usuário' },
    ],
  },
  {
    group: 'bko',
    name: 'Backoffice Operações',
    funcionalidades: [
      { name: 'Cadastro/Edição de Estabelecimento' },
      { name: 'Cadastro/Edição de Fornecedor' },
      { name: 'Consulta de Estabelecimento' },
      { name: 'Consulta de Fornecedor' },
      { name: 'Configurar Taxas' },
      { name: 'Cadastro de Usuário' },
    ],
  },
  {
    group: 'ec',
    name: 'Estabelecimento Administrador',
    funcionalidades: [
      { name: 'Visualizar Relatórios' },
      { name: 'Solicitar antecipação' },
      { name: 'Consultar antecipações realizadas' },
      { name: 'Consultar cessão' },
      { name: 'Indicar fornecedor' },
      { name: 'Consultar fornecedores vinculados' },
      { name: 'Consultar Dados Cadastrais' },
      { name: 'Consultar Taxas e Tarifas' },
    ],
  },
  {
    group: 'ec',
    name: 'Estabelecimento Financeiro',
    funcionalidades: [
      { name: 'Visualizar Relatórios' },
      { name: 'Solicitar antecipação' },
      { name: 'Consultar antecipações realizadas' },
      { name: 'Consultar cessão' },
      { name: 'Indicar fornecedor' },
      { name: 'Consultar fornecedores vinculados' },
      { name: 'Consultar Dados Cadastrais' },
      { name: 'Consultar Taxas e Tarifas' },
    ],
  },
  {
    group: 'ec',
    name: 'Estabelecimento Compras',
    funcionalidades: [
      { name: 'Visualizar Relatórios' },
      { name: 'Solicitar antecipação' },
      { name: 'Consultar antecipações realizadas' },
      { name: 'Consultar cessão' },
      { name: 'Indicar fornecedor' },
      { name: 'Consultar fornecedores vinculados' },
      { name: 'Consultar Dados Cadastrais' },
      { name: 'Consultar Taxas e Tarifas' },
    ],
  },
  {
    group: 'fc',
    name: 'Fornecedor Administrador',
    funcionalidades: [
      { name: 'Visualizar Relatórios' },
      { name: 'Solicitar antecipação' },
      { name: 'Consultar antecipações realizadas' },
      { name: 'Consultar cessão' },
      { name: 'Indicar estabelecimento' },
      { name: 'Consultar estabelecimento vinculados' },
      { name: 'Upload de estabelecimento' },
    ],
  },
  {
    group: 'fc',
    name: 'Fornecedor Financeiro',
    funcionalidades: [
      { name: 'Visualizar Relatórios' },
      { name: 'Solicitar antecipação' },
      { name: 'Consultar antecipações realizadas' },
      { name: 'Consultar cessão' },
      { name: 'Indicar estabelecimento' },
      { name: 'Consultar estabelecimento vinculados' },
      { name: 'Upload de estabelecimento' },
    ],
  },
  {
    group: 'fc',
    name: 'Fornecedor Comercial',
    funcionalidades: [
      { name: 'Visualizar Relatórios' },
      { name: 'Solicitar antecipação' },
      { name: 'Consultar antecipações realizadas' },
      { name: 'Consultar cessão' },
      { name: 'Indicar estabelecimento' },
      { name: 'Consultar estabelecimento vinculados' },
      { name: 'Upload de estabelecimento' },
    ],
  },
];
