export const tags: { [s: string]: string } = {
  'internal-server-error':
    'Não foi possível completar a ação. Se persistir o erro, entre em contato com o Administrador do Sistema.',
  'not-implemented': 'Serviço indisponível',
  'access-denied': 'Acesso negado',
  'usuario-ja-e-membro': 'Usuário já é membro',
  'error-keycloak-authenticate-as-admin': 'Houve um erro ao autenticar como administrador',
  'error-keycloak-generate-session-token': 'Houve um erro ao criar token da sessão',
  'error-keycloak-change-user-roles': 'Houve um erro ao atualizar acessos do usuário',
  'error-keycloak-get-roles-ids': 'Houve um erro ao buscar ids dos acessos',
  'error-keycloak-authenticate': 'Houve um erro ao autenticar',
  'error-keycloak-refresh-token': 'Houve um erro ao atualizar token',
  'error-keycloak-invite-user': 'Houve um erro ao convidar usuário',
  'error-keycloak-create-user': 'Houve um erro ao criar usuário',
  'error-keycloak-update-user-data': 'Houve um erro ao atualizar dados do usuário',
  'error-keycloak-update-user-status': 'Houve um erro ao atualizar status do usuário',
  'error-keycloak-change-user-pass': 'Houve um erro ao trocar senha do usuário',
  'error-keycloak-get-user': 'Houve um erro ao buscar o Usuário',
  'error-keycloak-put-user': 'Houve um erro ao atualizar o Usuário',
  'error-keycloak-recreate-user': 'Houve um erro ao recriar o Usuário no Keycloak',
  'error-keycloak-get-info-user': 'Houve um erro ao buscar as informações do usuário no Keycloak',
  'fornecedor-ja-indicado': 'Este fornecedor já foi indicado.',
  'empty-result-from-movidesk': 'Sem resposta do Movidesk',
  'cessao-nao-encontrada': 'Cessão não encontrada',
  'registro-nao-encontrato': 'Registro não encontrado',
  'credenciamento-status-invalido': 'Credenciamento com status inválido para ser alterado.',
  'file-not-exists': 'Arquivo não existe',
  'pre-credenciamento-existente': 'Já existe um pré-credenciamento para o documento informado.',
  'credenciamento-existente': 'Já existe um credenciamento para o documento informado.',
  'credenciamento-nao-localizado': 'Credenciamento não localizado',
  'estabelecimento-nao-encontrado': 'Estabelecimento não localizado',
  'participante-nao-encontrado': 'Participante não encontrado',
  'missing-participante': 'Participante não Informado',
  'invalid-participante-id': 'Identificador (id) de Participante inválido',
  'missing-credenciamento-id': 'O id do credenciamento não foi informado',
  'missing-document': 'O documento não foi informado',
  'movidesk-document-mismatch':
    'O documento do participante no Movidesk não corresponde ao documento atual.',
  'movidesk-username-exists-to-other-participant-id':
    'Usuário já cadastrado no Movidesk para outro Participante.',
  'missing-movidesk-code-reference': 'CodeReference do Movidesk não informado',
  'missing-email': 'O e-mail não foi informado',
  'fornecedor-ja-cadastrado': 'Já existe um fornecedor cadastrado com o documento informado.',
  'fornecedor-nao-encontrado': 'Fornecedor não encontrado',
  'valor-inicio-maior': 'O valor Inicio deve ser menor que o valor Final',
  'range-invalid': 'Os valores de Cessão coincidem-se.',
  'estabelecimento-ja-vinculado': 'Este estabelecimento já foi vinculado',
  'estabelecimento-ja-indicado': 'Este estabelecimento já foi indicado',
  'vinculo-nao-encontrado': 'Vínculo entre Estabelecimento/Fornecedor não localizado',
  'email-senha-invalido': 'E-mail ou senha inválido',
  'usuario-not-found': 'Usuário não encontrado',
  'usuario-keycloak-not-found': 'Usuário não encontrado no Keycloak.',
  'usuario-existente': 'Usuário existente',
  'fornecedor-ja-vinculado': 'Fornecedor já vinculado',
  'convite-invalido': 'Convite inválido',
  'invalid-sent-data': 'Dados inválidos',
  'cep-not-found': 'CEP não encontrado',
  'termo-nao-encontrado': 'Termo não encontrado.',
  'cessao-pendente-existente':
    'Não é possível solicitar outra cessão recorrente enquanto a anterior ainda está pendente de aprovação.',
  'cessao-recorrente-existente-no-mes':
    'Não é possível solicitar mais de uma cessão recorrente no mesmo mês.',
  'cessao-recorrente-existente-no-mes-vencimento':
    'Mês da data de vencimento coincide com outra cessão recorrente.',
  'recorrencia-expirada': 'A data de validade para cessões recorrentes expirou.',
  'recorrencia-invalida': 'Existe uma recorrência que ainda não foi aprovada.',
  'valor-solicitado-superior-valor-recorrente':
    'Valor da Cessão solicitada não pode ser superior ao Valor Máximo recorrente.',
  'data-expiracao-inferior-30-dias':
    'Data de validade da recorrência não pode ser menor que 30 dias a partir de hoje.',
  'valor-solicitado-superior-valor-disponivel':
    'Valor da Cessão solicitada não pode ser superior ao Valor Disponível para Cessão.',
  'data-expiracao-anterior-prox-dia': 'Data de Expiração deve ser a partir do próximo dia.',
  'data-expiracao-anterior-prox-dois-dias': 'Data de Vencimento deve ser superior a 2 dias.',
  'data-expiracao-posterior-vencimento':
    'Data de Expiração deve ser anterior à data de vencimento.',
  'status-recorrencia-invalido': 'Recorrência com status inválido para inclusão.',
  'taxa-not-found': 'Configuração de Taxas não encontrada',
  'taxa-overlaps':
    'Não pode haver sobreposição de vigência. Por favor tente com outras datas de início/término.',
  'missing-inicio-vigencia': 'Selecione a Vigência Inicial',
  'inicio-vigencia-invalid': 'O Início da Vigência deve ser a partir de amanhã',
  'termino-vigencia-invalid': 'O Término da Vigência deve ser após o Início da mesma',
  'data-pagamento-retroativa': 'A Data de Pagamento informada não pode ser retroativa.',
  'data-pagamento-nula': 'Data de Pagamento inválida.',
  'lista-recebiveis-vazia': 'Lista de recebíveis vazia.',
  'option-not-available': 'Opção indisponível. Por favor recarregue a página.',
  'invite-not-found': 'Convite não encontrado para esse email. Entre em contato com o solicitante.',
  'exportacao-indisponivel': 'A exportação selecionada não está disponível.',
  'data-inicio-nao-especificada': 'Selecione uma data de início para o filtro do relatório.',
  'data-fim-nao-especificada': 'Selecione uma data de fim para o filtro do relatório.',
  'periodo-data-invalido': 'O período informado é inválido.',
  'time-limit-exceeded': 'Solicitação de antecipação passou do horário limite',
  'anticipation-time-limit-exceeded': 'Solicitação de antecipação passou do horário limite',
  'anticipation-blocked-day': 'Solicitação de antecipação fora dos dias úteis',
  'faturamento-anual-desatualizado':
    'A sua opção de faturamento anual cadastrado está desativado em nosso sistema' +
    ', por favor, atualize seu faturamento anual',
  'tipoPessoa-invalido': 'O tipo de pessoa selecionado é inválido',
  'download-fichaCadastro': 'Erro ao fazer download do arquivo Ficha de Cadastro.',
  'download-comprovanteDeResidencia': 'Erro ao fazer download do arquivo Compovante de Residência.',
  'download-contratoSocial': 'Erro ao fazer download do arquivo Contrato Social.',
  'download-extratosBancarios': 'Erro ao fazer download do arquivo Extratos Bancários.',
  'prazo-aprovacao-dias': 'A data de expiração deve ser no mínimo de dois dias',
  'indicacao-status-invalido': 'O status da indicação é inválido para executar essa operação.',
  'indicacao-not-found': 'Indicação não encontrada.',
  'status-documento-0': 'Documento disponível',
  'status-documento-1': 'Existe um Pré-Cadastro com este Documento',
  'status-documento-2': 'Existe um Credenciamento Pendente com este Documento',
  'status-documento-3': 'Existe um Credenciamento Em Análise com este Documento',
  'status-documento-4': 'Existe um Credenciamento Aprovado com este Documento',
  'status-documento-5': 'Existe um Credenciamento Recusado com este Documento',
  'status-documento-6': 'Existe um Estabelecimento Ativo com este Documento',
  'status-documento-7': 'Existe um Estabelecimento Inativo com este Documento',
  'status-documento-8': 'Existe um Fornecedor Ativo com este Documento',
  'status-documento-9': 'Existe um Fornecedor Inativo com este Documento',
  'status-documento-10': 'Existe um Participante Ativo com este Documento',
  'status-documento-11': 'Existe um Participante Inativo com este Documento',
  'status-documento-12': 'Existe uma Indicação de Fornecedor em aberto para este Documento',
  'status-documento-13': 'Existe uma Indicação de Estabelecimento em aberto para este Documento',
  'no-role-supplied': 'Permissão não identificada',
  'convite-existente': 'O Convite já foi criado',
  'taxa-debito-invalida': 'A taxa de débito é invalida',
  'taxa-administrativa-invalida': 'A taxa administrativa é invalida',
  'documento-informado-diferente-do-existente': 'Documento informado é diferente do cadastrado',
  'username-ja-existe': 'Username existente',
};
